"""
Fast refresh — update DiscoPoP's dependence data without re-running the program
------------------------------------------------------------------------------
A full re-profile is three steps: instrument+compile, run the instrumented
binary, analyse.  Measured on this machine:

    example4 (tiny)            compile 1.80 s   run 0.37 s   explorer 6.49 s
    array_accumulator (104M)   compile 1.06 s   run 7.91 s   explorer 3.45 s

The run is the step that scales badly — 17x native on the second case, worse
the more memory traffic the program does — and it is the only step that needs
the program to actually execute.  Everything else is static.

What this module does is skip that step.  After a rewrite:

  * `discopop_cxx` runs again (cheap) and produces a FRESH `Data.xml`,
    `static_dependencies.txt` and `instructionID_to_lineID_mapping.txt` for the
    new source.
  * the previous run's DYNAMIC dependences are carried forward and translated
    onto the new instruction numbering — the part that has to be exactly right.
  * dependences the rewrite invalidated are DROPPED, never guessed.  The
    rewritten region is then covered by static dependences only, which are
    over-approximate: they can make the agent more conservative, never less.

Why the translation is delicate
-------------------------------
DiscoPoP numbers instructions from a single counter in module order, so an edit
renumbers everything after the first changed instruction (verified: an edit in
`bubble_sort` diverged the numbering at instruction 19, renumbering all of
`main` behind it).  `instructionID_to_lineID_mapping.txt` maps an instruction to
`file:line:col`, but it is MANY-to-one — ids 3, 6, 9 and 12 all map to `1:6:0` —
so it cannot simply be inverted.

The identity that works is `(file, line, column, k)` where k counts instructions
sharing that position, in id order.  It is stable because the numbering is
deterministic for identical source (verified: two compiles of the same file
produce byte-identical mapping files) and locally stable across an edit, since
instructions are emitted in source order.

Static memory-region ids are NOT stable — they are pointer-derived and differ
between two compiles of the same source (`S-1208730495` vs `S-1084334991`).
Only variable names are, which is exactly what DiscoPoP's own
`map_static_and_dynamic_dependencies()` matches on, so nothing here depends on
them.
"""
from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# `67@43 NOM  WAR 55@43|GEPRESULT_arr(4338667626) RAW 74@35|...`
# The number after `@` is callpath state, NOT a line — see _Translator.endpoint.
_INSTR_AT_STATE = re.compile(r"^(\d+)@(\d+)$")
_FILE_LINE = re.compile(r"^(\d+):(\d+)$")

Key = Tuple[str, int, int, int]      # file, line, column, occurrence


@dataclass
class RemapStats:
    """What survived the translation, and what did not.

    Reported rather than hidden: a fast refresh that silently dropped most of
    the profile would look identical to one that worked, and the difference is
    the whole reason to trust the evidence afterwards.
    """
    deps_in: int = 0
    deps_out: int = 0
    deps_dropped_changed: int = 0     # an endpoint sits in rewritten code
    deps_dropped_unmapped: int = 0    # the instruction no longer exists
    deps_static_dropped: int = 0      # static dep, regenerated by the new compile
    loops_in: int = 0
    loops_out: int = 0
    notes: List[str] = field(default_factory=list)

    def summary(self) -> str:
        return (f"{self.deps_out}/{self.deps_in} observed dependences carried "
                f"forward ({self.deps_dropped_changed} in rewritten code, "
                f"{self.deps_dropped_unmapped} no longer present; "
                f"{self.deps_static_dropped} static ones regenerated by the "
                f"compile), {self.loops_out}/{self.loops_in} loop trip counts")


def line_map(old_text: str, new_text: str) -> Dict[int, int]:
    """1-based old line -> new line, for lines the edit left untouched.

    Computed from the patch the agent itself applied rather than read from
    DiscoPoP's `line_mapping.json`, which is regenerated per profile and maps
    the current source to itself (verified: identity on example4).  A line that
    was changed or deleted is simply absent, and every dependence that mentions
    it is dropped.
    """
    old_lines = old_text.splitlines()
    new_lines = new_text.splitlines()
    out: Dict[int, int] = {}
    sm = difflib.SequenceMatcher(None, old_lines, new_lines, autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag != "equal":
            continue
        for off in range(i2 - i1):
            out[i1 + off + 1] = j1 + off + 1
    return out


def load_instruction_sequence(mapping_file: Path) -> List[Tuple[str, str]]:
    """The mapping file as an ordered [(instruction id, position)] list.

    Order matters and is the whole basis of the alignment below: DiscoPoP
    numbers instructions in module order, so the file is a faithful sequence of
    the program's instructions.  `*` entries — instructions with no source
    position — are KEPT here, unlike in the key index: roughly a fifth of the
    instructions have no position (36 of 178 on example4) and dependences do
    refer to them, so dropping them would strand those dependences.
    """
    seq: List[Tuple[str, str]] = []
    if not mapping_file.exists():
        return seq
    for raw in mapping_file.read_text().splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split()
        if len(parts) < 2:
            continue
        seq.append((parts[0], parts[1]))
    return seq


def build_id_map(
    old_map: Path, new_map: Path, lmap: Dict[int, int]
) -> Tuple[Dict[str, str], int]:
    """old instruction id -> new instruction id, by aligning the two mappings.

    Matching each instruction on `(file, line, column, occurrence)` looks
    natural and does not work: an instruction with no source position (`*`) has
    no such key, and there are plenty of them.  What does work is that both
    files are the SAME program's instructions in order, so this is an alignment
    problem, and the position strings — rewritten into new-line coordinates
    first, so an unchanged instruction reads identically on both sides — are
    exactly the tokens to align on.  `*` entries then match by context, the way
    a blank line does in a text diff.

    Instructions in code the rewrite touched are given a unique token so they
    can never match anything, which is what keeps their dependences out.

    Returns (map, number of old instructions that found no counterpart).
    """
    old_seq = load_instruction_sequence(old_map)
    new_seq = load_instruction_sequence(new_map)

    def normalise(pos: str, idx: int) -> str:
        if pos == "*":
            return "*"
        parts = pos.split(":")
        if len(parts) < 3:
            return pos
        try:
            line = int(parts[1])
        except ValueError:
            return pos
        new_line = lmap.get(line)
        if new_line is None:
            return f"\0changed{idx}"     # unique: never matches
        return f"{parts[0]}:{new_line}:{parts[2]}"

    old_tokens = [normalise(p, i) for i, (_, p) in enumerate(old_seq)]
    new_tokens = [p for _, p in new_seq]

    id_map: Dict[str, str] = {}
    sm = difflib.SequenceMatcher(None, old_tokens, new_tokens, autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag != "equal":
            continue
        for off in range(i2 - i1):
            id_map[old_seq[i1 + off][0]] = new_seq[j1 + off][0]
    return id_map, len(old_seq) - len(id_map)


def load_instruction_keys(mapping_file: Path) -> Tuple[Dict[str, Key], Dict[Key, str]]:
    """Read `instructionID_to_lineID_mapping.txt` into both directions.

    Returns (id -> key, key -> id).  Instructions with no source position (`*`)
    are skipped: they cannot be matched across a rebuild, and no dependence
    refers to them by position.
    """
    fwd: Dict[str, Key] = {}
    rev: Dict[Key, str] = {}
    seen: Dict[Tuple[str, int, int], int] = {}
    if not mapping_file.exists():
        return fwd, rev
    for raw in mapping_file.read_text().splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split()
        if len(parts) < 2 or parts[1] == "*":
            continue
        instr_id = parts[0]
        pos = parts[1].split(":")
        if len(pos) < 3:
            continue
        try:
            file_id, line, col = pos[0], int(pos[1]), int(pos[2])
        except ValueError:
            continue
        base = (file_id, line, col)
        k = seen.get(base, 0)
        seen[base] = k + 1
        key: Key = (file_id, line, col, k)
        fwd[instr_id] = key
        rev[key] = instr_id
    return fwd, rev


class _Translator:
    """old instruction id + old line -> new instruction id + new line."""

    def __init__(self, old_map: Path, new_map: Path, lmap: Dict[int, int]) -> None:
        self.old_fwd, _ = load_instruction_keys(old_map)
        self.new_fwd, self.new_rev = load_instruction_keys(new_map)
        self.id_map, self.unmatched = build_id_map(old_map, new_map, lmap)
        self.lmap = lmap

    def line(self, line: int) -> Optional[int]:
        return self.lmap.get(line)

    def instr(self, instr_id: str) -> Optional[str]:
        """The new id for an old instruction, or None if it did not survive.

        The alignment answers this.  When the old instruction had a source
        position, the answer is cross-checked against that position: the two
        methods are independent, so a disagreement means the alignment slipped
        and the dependence is dropped rather than attached to the wrong
        instruction.
        """
        new_id = self.id_map.get(instr_id)
        if new_id is None:
            return None
        old_key = self.old_fwd.get(instr_id)
        if old_key is not None:
            new_key = self.new_fwd.get(new_id)
            expected_line = self.lmap.get(old_key[1])
            if (new_key is None or expected_line is None
                    or new_key[1] != expected_line or new_key[2] != old_key[2]):
                return None
        return new_id

    def endpoint(self, token: str) -> Optional[str]:
        """Translate one dependence endpoint.

        Two forms appear in the file and they mean different things:

          `67@43`  instruction 67, plus callpath STATE information.  The number
                   after the `@` is not a line — instruction 67 sits at line 11
                   here — and the explorer strips it before use
                   (parser.py: `sink = sink[: sink.index("@")]  # remove state
                   information`).  So the instruction id is translated and the
                   state is carried through untouched; inventing a new state id
                   would be worse than keeping one the analysis discards.
          `1:18`   a plain fileID:lineID, which IS a source line.
        """
        m = _INSTR_AT_STATE.match(token)
        if m:
            new_instr = self.instr(m.group(1))
            if new_instr is None:
                return None
            return f"{new_instr}@{m.group(2)}"
        m = _FILE_LINE.match(token)
        if m:
            new_line = self.line(int(m.group(2)))
            if new_line is None:
                return None
            return f"{m.group(1)}:{new_line}"
        return None

    def endpoint_line(self, token: str) -> Optional[int]:
        """The OLD source line an endpoint refers to, for diagnosis only."""
        m = _INSTR_AT_STATE.match(token)
        if m:
            key = self.old_fwd.get(m.group(1))
            return key[1] if key else None
        m = _FILE_LINE.match(token)
        return int(m.group(2)) if m else None


def remap_dependencies(
    dep_text: str, old_map: Path, new_map: Path, lmap: Dict[int, int]
) -> Tuple[str, RemapStats]:
    """Translate a `dynamic_dependencies.txt` onto a new build of the source.

    Anything that cannot be translated with certainty is dropped.  That is the
    whole safety argument: a dependence carried onto the wrong instruction is
    worse than a dependence that is missing, because the missing one is covered
    by the static analysis while the wrong one silently misinforms it.
    """
    tr = _Translator(old_map, new_map, lmap)
    stats = RemapStats()
    out: List[str] = []

    for raw in dep_text.splitlines():
        line = raw.rstrip("\n")
        if not line.strip():
            continue
        fields = line.split()

        # `START 1:18`
        if fields[0] == "START" and len(fields) > 1:
            moved = tr.endpoint(fields[1])
            if moved:
                out.append(f"START {moved}")
            continue

        # `1:8 BGN loop 131328 512 256 512` / `1:15 END loop`
        if len(fields) >= 3 and fields[1] in ("BGN", "END") and fields[2] == "loop":
            if fields[1] == "BGN":
                stats.loops_in += 1
            moved = tr.endpoint(fields[0])
            if moved is None:
                continue          # a loop inside rewritten code: no valid counts
            if fields[1] == "BGN":
                stats.loops_out += 1
            out.append(" ".join([moved] + fields[1:]))
            continue

        # `0:130 BGN func 1:6` — the trailing token is the function's line
        if len(fields) >= 4 and fields[1] in ("BGN", "END") and fields[2] == "func":
            moved = tr.endpoint(fields[3])
            if moved is None:
                continue
            out.append(" ".join(fields[:3] + [moved] + fields[4:]))
            continue

        # `<sink> NOM  <TYPE> <source>|<var>(<region>) [<TYPE> <source>|...]`
        if len(fields) >= 4 and fields[1] == "NOM":
            # STATIC dependences also live in this file, written with a bare
            # instruction id and an `S-` memory region.  They are dropped rather
            # than translated: the new compile has just regenerated all of them
            # for the new code, and the explorer reads that file separately
            # (parser.py concatenates static_dependencies.txt with this one), so
            # carrying stale copies would duplicate every one of them under an
            # id that now means something else.
            if "@" not in fields[0] and ":" not in fields[0]:
                stats.deps_static_dropped += 1
                continue

            stats.deps_in += 1
            sink = tr.endpoint(fields[0])
            if sink is None:
                # Distinguish the two reasons, because they mean different
                # things about the refresh: "in rewritten code" is expected and
                # covered by static analysis, "no longer present" is not.
                old_line = tr.endpoint_line(fields[0])
                if old_line is not None and old_line not in lmap:
                    stats.deps_dropped_changed += 1
                else:
                    stats.deps_dropped_unmapped += 1
                continue

            kept: List[str] = []
            i = 2
            while i + 1 < len(fields) + 1 and i < len(fields):
                dep_type = fields[i]
                if i + 1 >= len(fields):
                    break
                payload = fields[i + 1]
                i += 2
                if "|" not in payload:
                    continue
                src_tok, _, var_part = payload.partition("|")
                # `INIT *|arr(...)` and `INIT 0@0|...` both mean "defined here,
                # with no originating instruction".  Instruction 0 is a sentinel,
                # not a real id, so it is passed through rather than looked up.
                if src_tok in ("*", "0@0"):
                    kept.append(f"{dep_type} {src_tok}|{var_part}")
                    continue
                new_src = tr.endpoint(src_tok)
                if new_src is None:
                    continue
                kept.append(f"{dep_type} {new_src}|{var_part}")

            if not kept:
                stats.deps_dropped_changed += 1
                continue
            out.append(f"{sink} NOM  " + " ".join(kept))
            stats.deps_out += 1
            continue

        # Anything unrecognised is passed through untouched rather than guessed at.
        out.append(line)

    return "\n".join(out) + "\n", stats


def remap_loop_counters(text: str, lmap: Dict[int, int]) -> str:
    """Translate `loop_counter_output.txt` (`fileID line count`) onto new lines.

    Trip counts drive the workload score and the granularity advice in the
    prompt.  A loop whose header moved keeps its count; one inside rewritten
    code loses it and is scored from static information only.
    """
    out: List[str] = []
    for raw in text.splitlines():
        fields = raw.split()
        if len(fields) != 3:
            continue
        try:
            new_line = lmap.get(int(fields[1]))
        except ValueError:
            continue
        if new_line is None:
            continue
        out.append(f"{fields[0]} {new_line} {fields[2]}")
    return "\n".join(out) + ("\n" if out else "")


def remap_reduction(text: str, lmap: Dict[int, int]) -> str:
    """Translate `reduction.txt`, whose first two fields are `fileID line`."""
    out: List[str] = []
    for raw in text.splitlines():
        fields = raw.split()
        if len(fields) < 2:
            continue
        try:
            new_line = lmap.get(int(fields[1]))
        except ValueError:
            continue
        if new_line is None:
            continue
        out.append(" ".join([fields[0], str(new_line)] + fields[2:]))
    return "\n".join(out) + ("\n" if out else "")


def verify_translation(
    old_text: str, new_text: str, lmap: Dict[int, int],
) -> List[str]:
    """Sanity-check the line map against the two source files themselves.

    Cheap, and it catches the failure that would otherwise be invisible: every
    line the map claims is unchanged must actually read the same in both files.
    """
    old_lines = old_text.splitlines()
    new_lines = new_text.splitlines()
    problems: List[str] = []
    for old_ln, new_ln in lmap.items():
        if not (1 <= old_ln <= len(old_lines)) or not (1 <= new_ln <= len(new_lines)):
            problems.append(f"line {old_ln}->{new_ln} is out of range")
            continue
        if old_lines[old_ln - 1] != new_lines[new_ln - 1]:
            problems.append(
                f"line {old_ln}->{new_ln} claims unchanged but differs: "
                f"{old_lines[old_ln - 1]!r} vs {new_lines[new_ln - 1]!r}"
            )
    return problems
