"""
Mock LLM — returns pre-computed diffs for demo hotspots.

Used with --mock-llm to test the full agent flow (L4 validation,
re-profiling, re-exploration) without a live API key.

Each diff is what a real LLM should produce for the given hotspot:

  compute_prefix_sum (example3) — replace recursive + global-state algorithm
                      with iterative Hillis-Steele two-buffer scan.
                      Removes global running_total dependency → Do-All inner loop.

  scalar_transform  (example2) — privatise `temp` (move declaration inside loop)
                      removes the WAR dependency → Do-All

  normalize_fused   (example2) — loop fission: max-reduction pass then do-all divide
                      removes loop-carried max_val dep → Reduction + Do-All

  dot_fused         (example2) — loop fission: do-all squared[] then reduction *dot
                      separates the mixed pattern → Do-All + Reduction
"""
from __future__ import annotations

from typing import Optional

from .types import EvidencePackage

# ---------------------------------------------------------------------------
# Pre-computed diffs (what the LLM should produce)
# ---------------------------------------------------------------------------

# Diff for compute_prefix_sum (example3/recursive_prefix.cpp, function starts line 9).
# Generated by:  diff -u before.cpp after.cpp
# Replaces the recursive + global-state algorithm with an iterative
# Hillis-Steele two-buffer parallel prefix scan.
# After re-profiling, the inner scan loop becomes a Do-All candidate.
_DIFF_RECURSIVE_PREFIX = (
    "--- example3/recursive_prefix.cpp\n"
    "+++ example3/recursive_prefix.cpp\n"
    "@@ -1,18 +1,23 @@\n"
    " #include <stdio.h>\n"
    " #include <stdlib.h>\n"
    "+#include <string.h>\n"
    " \n"
    "-// Global shared state — creates a chain of RAW dependencies\n"
    "-int running_total = 0;\n"
    "-\n"
    "-// Recursive function: each call MUST read the result of the previous one.\n"
    "-// No pragma can help here — the dependency is baked into the algorithm.\n"
    "-void compute_prefix_sum(int *arr, int *result, int i, int n) {\n"
    "-    if (i == n) return;\n"
    "-\n"
    "-    running_total += arr[i];   // reads & writes shared state\n"
    "-    result[i] = running_total; // result[i] depends on result[i-1]\n"
    "-\n"
    "-    compute_prefix_sum(arr, result, i + 1, n); // tail-recursive, sequential\n"
    "+// Hillis-Steele parallel prefix scan.\n"
    "+// Outer loop (stride d) is sequential; inner loop is Do-All:\n"
    "+//   each iteration reads only from the frozen prev[] buffer\n"
    "+//   and writes to an independent cur[i] slot.\n"
    "+void compute_prefix_sum(int *arr, int *result, int n) {\n"
    "+    int *buf  = (int *)malloc(n * sizeof(int));\n"
    "+    int *cur  = result;\n"
    "+    int *prev = buf;\n"
    "+    for (int i = 0; i < n; i++) cur[i] = arr[i];\n"
    "+    for (int d = 1; d < n; d *= 2) {\n"
    "+        int *tmp = cur; cur = prev; prev = tmp;\n"
    "+        for (int i = 0; i < n; i++)\n"
    "+            cur[i] = (i >= d) ? prev[i] + prev[i - d] : prev[i];\n"
    "+    }\n"
    "+    if (cur != result) memcpy(result, cur, n * sizeof(int));\n"
    "+    free(buf);\n"
    " }\n"
    " \n"
    " int main(void) {\n"
    "@@ -20,7 +25,7 @@\n"
    "     int n        = 8;\n"
    "     int result[8];\n"
    " \n"
    "-    compute_prefix_sum(arr, result, 0, n);\n"
    "+    compute_prefix_sum(arr, result, n);\n"
    " \n"
    "     for (int i = 0; i < n; i++)\n"
    '         printf("%d ", result[i]);  // → 3 4 8 9 14 23 25 31\n'
    '     printf("\\n");\n'
    " }\n"
)

# Diff for scalar_transform: move `float temp` inside the loop.
# Removes the WAR dependency on the shared stack slot.
_DIFF_SCALAR_TRANSFORM = """\
--- example2/example2.cpp
+++ example2/example2.cpp
@@ -40,8 +40,7 @@
 /* ── Hotspot 1: scalar_transform ────────────────────────────────────────── */
 void scalar_transform(const float *arr, float *out, int n) {
-    float temp;                          /* WAR: shared stack slot across iters */
     for (int i = 0; i < n; i++) {
-        temp   = arr[i] * arr[i] + 1.0f;
+        float temp = arr[i] * arr[i] + 1.0f;
         out[i] = temp / (arr[i] + 1.0f);
     }
 }
"""

# Diff for normalize_fused: loop fission.
_DIFF_NORMALIZE_FUSED = """\
--- example2/example2.cpp
+++ example2/example2.cpp
@@ -49,9 +49,8 @@
 /* ── Hotspot 2: normalize_fused ─────────────────────────────────────────── */
 void normalize_fused(const float *arr, float *out, int n) {
     float max_val = arr[0];
-    for (int i = 0; i < n; i++) {
-        if (arr[i] > max_val)
-            max_val = arr[i];            /* loop-carried conditional write    */
-        out[i] = arr[i] / max_val;       /* reads loop-carried max_val        */
-    }
+    for (int i = 1; i < n; i++)
+        if (arr[i] > max_val) max_val = arr[i];
+    for (int i = 0; i < n; i++)
+        out[i] = arr[i] / max_val;
 }
"""

# Diff for dot_fused: loop fission.
_DIFF_DOT_FUSED = """\
--- example2/example2.cpp
+++ example2/example2.cpp
@@ -59,8 +59,8 @@
 /* ── Hotspot 3: dot_fused ───────────────────────────────────────────────── */
 void dot_fused(const int *a, const int *b, int *squared, long *dot, int n) {
-    *dot = 0L;
-    for (int i = 0; i < n; i++) {
-        squared[i] = a[i] * a[i];        /* do-all write                      */
-        *dot      += (long)(a[i] * b[i]);/* reduction — mixes with above      */
-    }
+    for (int i = 0; i < n; i++)
+        squared[i] = a[i] * a[i];
+    *dot = 0L;
+    for (int i = 0; i < n; i++)
+        *dot += (long)(a[i] * b[i]);
 }
"""

# Diff for bubble_sort (example4/bubble_sort.cpp, inner loop starts line 23).
# Replaces bubble sort (cross-iteration swap deps) with odd-even transposition sort.
# Each inner phase (even/odd) is a genuine Do-All: step=2 means no index overlaps.
# Generated by: diff -u bubble_sort.cpp bs_after.cpp (header paths normalised).
_DIFF_BUBBLE_SORT = "--- example4/bubble_sort.cpp\n+++ example4/bubble_sort.cpp\n@@ -4,23 +4,19 @@\n #define N 1024\n \n /*\n- * Bubble sort — inner loop has a cross-iteration swap dependency.\n+ * Odd-even transposition sort — LLM restructured from bubble sort.\n  *\n- * Iteration i  writes arr[i] and arr[i+1].\n- * Iteration i+1 reads  arr[i+1] (just written by iteration i).\n+ * Each pass has two independent phases:\n+ *   Even phase: compares (0,1), (2,3), (4,5) ... no overlap → Do-All\n+ *   Odd  phase: compares (1,2), (3,4), (5,6) ... no overlap → Do-All\n  *\n- * This is a RAW dependency: the inner loop is NOT safe to parallelize.\n- * DiscoPoP will incorrectly label it as Do-All (applicable=True).\n- * Applying the pragma causes races on arr[i+1] at thread-chunk boundaries.\n- * TSan catches it → Tier-1 validation FAILS → agent escalates to Tier-2.\n- *\n- * LLM restructures to odd-even transposition sort:\n- *   Even phase: independent pairs (0,1), (2,3), (4,5) ... → Do-All\n- *   Odd  phase: independent pairs (1,2), (3,4), (5,6) ... → Do-All\n+ * Each inner loop is a genuine Do-All: iteration i only touches\n+ * arr[i] and arr[i+1], which are disjoint across iterations (step=2).\n  */\n void bubble_sort(int *arr, int n) {\n-    for (int pass = 0; pass < n - 1; pass++) {\n-        for (int i = 0; i < n - pass - 1; i++) {\n+    for (int pass = 0; pass < n; pass++) {\n+        int start = pass % 2;\n+        for (int i = start; i + 1 < n; i += 2) {\n             if (arr[i] > arr[i + 1]) {\n                 int tmp   = arr[i];\n                 arr[i]    = arr[i + 1];\n"

# Map region start-line → diff
_DIFFS_BY_START_LINE = {
    9:  _DIFF_RECURSIVE_PREFIX,   # compute_prefix_sum in example3/recursive_prefix.cpp
    23: _DIFF_BUBBLE_SORT,        # bubble_sort inner loop in example4/bubble_sort.cpp
    43: _DIFF_SCALAR_TRANSFORM,   # scalar_transform in example2/example2.cpp
    52: _DIFF_NORMALIZE_FUSED,    # normalize_fused in example2/example2.cpp
    62: _DIFF_DOT_FUSED,          # dot_fused in example2/example2.cpp
}


# ---------------------------------------------------------------------------
# Public API (same signature as l3_llm.call_llm)
# ---------------------------------------------------------------------------

def call_mock(evidence: EvidencePackage) -> Optional[str]:
    """Return the pre-computed diff for this region, or None if unknown."""
    diff = _DIFFS_BY_START_LINE.get(evidence.start_line)
    if diff:
        print(f"│  [Mock-LLM] Returning pre-computed diff for region {evidence.region_id} (line {evidence.start_line})")
    else:
        print(f"│  [Mock-LLM] No pre-computed diff for region {evidence.region_id} (line {evidence.start_line}) — skipping")
    return diff
